### ISSUE TITLE
Setup CAN bus on our Jetson AGX Orin

### ISSUE THREAD

**Issue by umnrobotics** [GOFIRST-Robotics/Lunabotics-2024#1]
Wire up the CAN transceivers and configure CAN communication on the Jetson.

**Comment by umnrobotics** [comment]
DONE: Wire & configure the CAN bus
IN-PROGRESS: auto start can bus communication on boot (after this is accomplished we can close this issue)

**Comment by RobHairson** [comment]
Can bus now starts on boot, how this was done has been added to readme

**Comment by umnrobotics** [comment]
[Link to CAN commands](https://docs.nvidia.com/jetson/archives/r34.1/DeveloperGuide/text/HR/ControllerAreaNetworkCan.html?highlight=can%20bus#important-features)
