### ISSUE TITLE
Create a camera app/frontend for Gstreamer that uses AV1 decoding

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/Lunabotics-2024#16]

**Comment by Isopod00** [comment]
This probably isn't super important, but it would be cool to look into / it would be a cool side project type of thing

**Comment by jmblixt3** [comment]
Gatreamer apt repository for Ubuntu 22.04 uses an old build of gstreamer which doesn't have much support for AV1. It will either need to be built from source or run in a container

**Comment by Isopod00** [comment]
We decided to run it in a container for now, so we should probably make sure that this camera frontend is a terminal cli app that can be run in the container as well

**Comment by Isopod00** [comment]
This is being developed in the [gstreamer-client ](https://github.com/GOFIRST-Robotics/Lunabotics-2024/tree/gstreamer-client) branch. @jmblixt3, what work is left to complete on this?

**Comment by jmblixt3** [comment]
It currently is using fake cameras and just toggling back in forth based on time

**Comment by jmblixt3** [comment]
We'll need to determine how we want to message pass between client and server to toggle cameras

**Comment by jmblixt3** [comment]
Decision was to use ros node to do this

**Comment by Isopod00** [comment]
This issue also includes making a launch file for the team laptop that starts the joystick node and also Jonathan's gstreamer camera client. This launch file is done and has been tested: it works!

**Comment by jmblixt3** [comment]
Ask Peter M he was testing it
