### ISSUE TITLE
Team Laptops Setup

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics-2024#9]
Clone our repository on these laptops and make sure that it builds! (Done)

**Remaining Tasks:**
-Install Solidworks on both laptops
-Setup the Nvidia ISAAC container on both laptops

**Comment by jmblixt3** [comment]
Make sure to add Nvidia docker setup on laptops (In-Progress)

**Comment by umnrobotics** [comment]
ROS, VScode, and Git have been installed on both! Still need to setup the Nvidia docker container
